GET http://localhost:3000/messages

###

POST http://localhost:3000/messages
Content-Type: application/json

{
    "name": "UserName1",
    "text": "MessageText1111",
}

###

DELETE http://localhost:3000/messages/4
Content-Type: application/json