GET http://localhost:3000/users

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "UserName6",
    "password": "password6"
}

###

PATCH  http://localhost:3000/users
Content-Type: application/json

{
    "name": "UserName6",
    "password": "password6"
}

###

PUT http://localhost:3000/users/2
Content-Type: application/json

{
    "name": "UserName6",
    "password": "password6"
}

###

DELETE http://localhost:3000/users/4
Content-Type: application/json